export enum DomainExceptionCode {
	DEFAULT_DOMAIN_EXCEPTION = 'DEFAULT_DOMAIN_EXCEPTION',
	RESERVATION_GUID_INVALID = 'RESERVATION_GUID_INVALID',
	RESERVATION_NOT_FOUND = 'RESERVATION_NOT_FOUND',
	RESERVATION_NUMBER_REQUIRED = 'RESERVATION_NUMBER_REQUIRED',
	RESERVATION_NUMBER_INVALID = 'RESERVATION_NUMBER_INVALID',
	RESERVATION_DATE_START_REQUIRED = 'RESERVATION_DATE_START_REQUIRED',
	RESERVATION_DATE_START_INVALID = 'RESERVATION_DATE_START_INVALID',
	RESERVATION_DATE_END_REQUIRED = 'RESERVATION_DATE_END_REQUIRED',
	RESERVATION_DATE_END_INVALID = 'RESERVATION_DATE_END_INVALID',
	RESERVATION_USER_ID_REQUIRED = 'RESERVATION_USER_ID_REQUIRED',
}

export abstract class DomainException extends Error {
	constructor(message?: string) {
		super(message)
		this.name = DomainExceptionCode.DEFAULT_DOMAIN_EXCEPTION
	}
}
